project_name: wpds

builds:
  - binary: wpds

    env:
      - CGO_ENABLED=0

    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - arm
      - arm64
      - 386

    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: 386

archive:

  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  format_overrides:
    - goos: windows
      format: zip

  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS

  files:
    - README.md
    - LICENSE

checksum:

  name_template: "{{ .ProjectName }}_checksums.txt"

release:

  draft: true