project_name: wpds

builds:
  - binary: wpds
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386

archive:

  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  format_overrides:
    - goos: windows
      format: zip

  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS

checksum:
  # You can change the name of the checksums file.
  # This is parsed with Golang template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Tag with the `v` prefix stripped)
  # The default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`
  name_template: "{{ .ProjectName }}_checksums.txt"